In [1]:
import warnings, sys, os, gc
from os.path import join
warnings.filterwarnings("ignore")
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# import torch; print(torch.cuda.is_available())

# import libemg
# from libemg.datasets import get_dataset_list
# from libemg.feature_extractor import FeatureExtractor

import numpy as np, pandas as pd
import random, copy, time
from sklearn.utils.class_weight import compute_class_weight
import matplotlib.pyplot as plt

from utils import *
from models import CNN

SEED = 13; random.seed(SEED); np.random.seed(SEED)
GENERATOR = torch.manual_seed(SEED)
MMAP_MODE = 'r'; SAVE_CHKP = True

In [2]:
NAME = 'cnn_raw_within'
res = np.load((f"{CHECKPOINT_PATH}/{NAME}/results.npy"), allow_pickle=True)
df = pd.DataFrame(res.tolist())
df.describe()

         acc_mean  act_acc_mean  bal_acc_mean
count  612.000000    612.000000    612.000000
mean    92.128363     79.752019     82.887769
std      5.661632     10.247126      8.478847
min     65.688291     29.978858     43.592516
25%     89.896071     73.680254     77.800962
50%     93.651849     80.678075     83.573784
75%     96.025242     87.357544     89.301353
max     99.865940     99.721991     99.715422

In [3]:
NAME = 'cnn_raw_within_lim'
res = np.load((f"{CHECKPOINT_PATH}/{NAME}/results.npy"), allow_pickle=True)
df = pd.DataFrame(res.tolist())
df.describe()

         acc_mean  act_acc_mean  bal_acc_mean
count  612.000000    612.000000    612.000000
mean    89.323774     60.039244     67.032250
std      5.914171     13.691667     11.281663
min     47.545708     23.072178     36.004740
25%     86.145761     49.456670     58.380527
50%     90.441113     59.690602     66.518304
75%     93.743982     70.748005     75.862475
max     99.696130     97.842835     98.363817

In [5]:
NAME = 'cnn_raw_within_ft'
res = np.load((f"{CHECKPOINT_PATH}/{NAME}/results.npy"), allow_pickle=True)
df = pd.DataFrame(res.tolist())
df.describe()

         acc_mean  act_acc_mean  bal_acc_mean
count  612.000000    612.000000    612.000000
mean    93.990072     82.806187     85.772437
std      4.709764      9.796368      8.078556
min     60.786953     33.279936     46.334077
25%     92.188944     77.701026     81.348274
50%     95.322847     84.347404     87.333763
75%     97.340449     90.006079     91.855729
max     99.865940     99.768875     99.799987